version: "3.9"  # optional since v1.27.0
services:
  app: 
    build: 
      dockerfile: Dockerfile
      context: .
    environment: 
      NODE_ENV: development
      JWT_SECRET: this-is-my-secret
      PORT: 4000
    ports: 
      - "8081:4000"
    volumes:
      - /usr/src/app/node_modules
volumes:
  logvolume01: {}